### PR TITLE
Automated docker builds on webhook

### PR DESCRIPTION
**Pull request by finitud**
Now that #1 is merged and the deployer is deployed and running, this PR hooks up the actual docker image build when we receive a successful travis build notification.

### CODE REVIEW

**Comment by seanh** [comment]
I'd have broken this into three separate commits (the logging changes, reading from env, and actually calling deploy), but otherwise lgtm

**Comment by finitud** [comment]
Makes sense. I squashed all the commits I had in this branch cause they were a bit messy, but will separate them a bit for better history clarity.

**Comment by finitud** [comment]
This should be much clearer.

**Comment by seanh** [comment]
LGTM, @chdorner ?

**Comment by chdorner** [comment]
LGTM. Make sure to add the `DOCKER_USERNAME` and `DOCKER_PASSWORD` to the relevant files in the playbook repo.

**Pull request merged**
